http:
  port: 8080
  timeout: 30s  # HTTP server read/write timeout

database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  name: ads

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

logger:
  level: dev

tracing:
  endpoint: "localhost:4318"
  service_name: "ad-service"
  environment: "development"
  version: "1.0.0"