services:
  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONFIG_FILE=/app/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
      - jaeger
      - otel-collector

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ads
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-config.yml:/otel-local-config.yml
    command: ["--config", "/otel-local-config.yml"]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "55678:55678"
      - "55679:55679"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250:14250"
      - "6831:6831/udp"
  prometheus:
      image: prom/prometheus:latest
      volumes:
        - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      ports:
        - 9090:9090

volumes:
  mysql-data:
